trigger:
- main

variables:
  appDir: BlurbClient

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- script: |
    cd BlurbClient
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(18d07810-bd20-491d-95cd-4ea8dbdbe96b)'
    appType: 'webApp'
    WebAppName: 'blurbs'
    packageForLinux: '$(appDir)/dist/*'